### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by CVer-Yang** [yangcong356/BITA#1]
您好, 请问哪里能够下载到这篇论文，想来学习一下

**Comment by wjltoyyyy** [comment]
您好，请问如何使用直接训练好的checkpoint生成image caption，您还保留着相关的demo吗？

**Comment by yangcong356** [comment]
@wjltoyyyy 我将会在下周更新相关代码。

**Comment by wjltoyyyy** [comment]
非常感谢！

**Comment by wjltoyyyy** [comment]
您好，请问您还会更新这部分代码吗？

**Comment by yangcong356** [comment]
@wjltoyyyy We have already updated the evaluation code. Please refer to the Readme file.

**Comment by wjltoyyyy** [comment]
@yangcong356 Thank you very much!

**Comment by wjltoyyyy** [comment]
您好，我这边生成图像注释都是of和the组成的句子，您知道是什么原因造成的吗？

**Comment by yangcong356** [comment]
@wjltoyyyy Did you update the weights under the "pretrained" and "finetuned" keys in the “bita_caption_opt2.7b.yaml” file with the trained weights I provided?
![Uploading 截屏2024-06-04 11.25.54.png…]()

**Comment by yangcong356** [comment]
@wjltoyyyy Did you update the weights under the "pretrained" and "finetuned" keys in the “bita_caption_opt2.7b.yaml” file with the trained weights I provided?
<img width="1013" alt="截屏2024-06-04 11 25 54" src="https://github.com/yangcong356/BITA/assets/39213788/54cf9605-bca4-4a35-a226-ecf3e7f9e7a2">

**Comment by yangcong356** [comment]
If you have any other questions, please open a new issue.
