### ISSUE TITLE
Seeking help with model issues

### ISSUE THREAD

**Issue by wuhuqifeixzy** [yangcong356/BITA#4]
"Could you please provide the model links used in the article? Due to network restrictions, we are unable to directly obtain the models from the Hugging Face library（in code）, and the models downloaded from online sources do not match your pre-trained results."

**Comment by yangcong356** [comment]
1. Regarding the issue of mismatched dimensions between the weights of the large language model you loaded and the model used in BITA, I have already provided an answer in the previous [issue 3](https://github.com/yangcong356/BITA/issues/3). I have also informed you which file, which key, and which large language model (facebook/opt-2.7b) to use.

2. Please download the weights for the large language model yourself. If you are unable to connect to Hugging Face, either use a proxy to download them or find an alternative solution through Google.

3. Finally, please read the paper carefully. We have already detailed the experimental setup in the paper.
