### ISSUE TITLE
可以用百度网盘分享一下NWPU，RSICD和UCM测试文件吗

### ISSUE THREAD

**Issue by YiguoHe** [yangcong356/BITA#5]
同仁您好！你们的工作非常优秀，所以鄙人想要follow一下。为了进行性能对比，希望能够用到你们使用的NWPU，RSICD和UCM测试集。但是onedrive上面无法下载你们分享的文件，原因是里面的小文件太多，超过了官方设置的限定。
所以不知道能不能麻烦你们用百度网盘之类的途径分享一下，我将不胜感激！谢谢！

**Comment by yangcong356** [comment]
@YiguoHe Thank you for recognizing this work! I’ve added the [Baidu Netdisk download link](https://pan.baidu.com/s/1y5IYbeE_qLfAEbq_hJsd2Q?pwd=kcq8) for the dataset in the ReadMe file.

**Comment by YiguoHe** [comment]
> @YiguoHe Thank you for recognizing this work! I’ve added the [Baidu Netdisk download link](https://pan.baidu.com/s/1y5IYbeE_qLfAEbq_hJsd2Q?pwd=kcq8) for the dataset in the ReadMe file.

Thank you very much for your generosity and kindness! We will actively cite your paper in our future work. Wish you a Merry Christmas Eve!
